INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('1', '1', 'Db & Web');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('1', '2', 'IT & Cloud');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('1', '3', 'Math');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('2', '4', 'Economy');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('2', '5', 'Finance');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('2', '10', 'Finance');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('3', '6', 'Anatomy');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('3', '7', 'Chemistry');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('3', '8', 'Basic surgery');
INSERT INTO course(fkCodeDepartment, fkTeacherCode, courseName) VALUES ('1', '2', 'NetWork');